---
roles:
  - src: git@github.com:rhattox-ansible/ansible-containerd
    scm: git
    version: main
    name: ansible-containerd

  - src: git@github.com:rhattox-ansible/ansible-containerd-nerdctl
    scm: git
    version: main
    name: ansible-containerd-nerdctl

  - src: git@github.com:rhattox-ansible/ansible-kubernetes
    scm: git
    version: main
    name: ansible-kubernetes
